name: scdiffusion
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - pytorch-cuda=11.7
  - pytorch=1.13.0
  - numpy=1.23.4
  - anndata=0.8.0
  - scanpy=1.9.1
  - scikit-learn=1.2.2
  - blobfile=2.0.0
  - pandas=1.5.1
  # - celltypist=1.3.0 doesn't work with numpy 1.23.4
  - imbalanced-learn=0.11.0
  - ipykernel
  - mpi4py=3.1.4
  - mkl=2024.0 # pytorch import error; could be conda / python version related
  - matplotlib<3.7 # scanpy wrong dependencies; possibly conda's fault?
